filebeat.config.prospectors:
  enabled: true
  path: conf.d/*.yml
 
 
output.kafka:
  # Boolean flag to enable or disable the output module.
  #enabled: true
 
  # The list of Kafka broker addresses from where to fetch the cluster metadata.
  # The cluster metadata contain the actual Kafka brokers events are published
  # to.
  #hosts: ["localhost:9092"]
  hosts: ["172.21.100.75:9092","172.21.100.76:9092","172.21.100.77:9092"]
   
  topic: '%{[type]}'
  partition.round_robin:
    # If enabled, events will only be published to partitions with reachable
    # leaders. Default is false.
    reachable_only: false
